Custom asset implementation and upgraded trading-pair
Polkadex-Substrate/polkadex-engine pull request #1
Opened 2020-12-08 11:03 UTC by ksr30

2020-12-08 11:45 UTC, Gauthamastro requested changes

2020-12-08 11:45 UTC, Gauthamastro commented on src/lib.rs
>          (quote_asset_id, base_asset_id).using_encoded(<T as frame_system::Trait>::Hashing::hash)
this is wrong, It should be like if base_id < quote_id then (base_id,quote_id) else (quote_id,base_id). This is how we derive the trading pair

2020-12-08 11:45 UTC, Gauthamastro commented on src/mock.rs
> +    pallet_generic_asset::GenesisConfig::<Test> {
We need to change this to custom_assets.

2020-12-08 11:45 UTC, Gauthamastro commented on src/tests.rs
> +use frame_support::{assert_noop, assert_ok};
We need to convert the test cases to custom_assets too

2020-12-08 11:50 UTC, ksr30 commented on src/lib.rs
>          (quote_asset_id, base_asset_id).using_encoded(<T as frame_system::Trait>::Hashing::hash)
actually I forgot to remove that ... we are not using that function

2020-12-08 11:54 UTC, ksr30 commented on src/lib.rs
>          (quote_asset_id, base_asset_id).using_encoded(<T as frame_system::Trait>::Hashing::hash)
check https://github.com/Polkadex-Substrate/polkadex-engine/blob/feature/DEX-204.06/src/lib.rs#L527

2020-12-12 06:39 UTC, Gauthamastro commented on src/lib.rs
>          (quote_asset_id, base_asset_id).using_encoded(<T as frame_system::Trait>::Hashing::hash)
Okay got it.

2020-12-12 06:41 UTC, Gauthamastro requested changes
Implement Custom Assets in Mock.rs and Tests.rs

2020-12-12 06:50 UTC, ksr30 commented
yea .. I will do it after altogether

2020-12-21 15:54 UTC, merged